Required:
  receptor: test_receptor_topology_RNA.pdb
  ligand: ligand.sdf
  ligand_batch: null
  center: [-12.097, 34.025, 1278.974]
Advanced:
  exhaustiveness: 512
  randomize: true
  mc_steps: 20
  opt_steps: -1
  refine_steps: 5
  num_pose: 10
  rmsd_limit: 1.0
  energy_range: 3.0
  seed: 12345
  use_tor_lib: false
Hardware:
  gpu_device_id: 0
Settings:
  box_size: [30.0, 30.0, 30.0]
  task: screen
  search_mode: balance
Preprocessing:
  template_docking: true
  reference_sdf_file_name: reference.sdf
  compute_center: true
  core_atom_mapping_dict_list: null
  covalent_ligand: false
  covalent_residue_atom_info_list: null
  preserve_receptor_hydrogen: false
  temp_dir_name: /tmp
  output_docking_pose_sdf_file_name: unidock2_pose.sdf
