c_compiler:
- gcc
cxx_compiler:
- gxx
c_compiler_version:
- '11'
cxx_compiler_version:
- '11'
c_stdlib:
- sysroot
c_stdlib_version:
- '2.17'
channel_sources:
- http://quetz.dp.tech:8088/get/baymax conda-forge
channel_targets:
- http://quetz.dp.tech:8088/get/baymax conda-forge main
cuda_compiler:
- cuda-nvcc
target_platform:
- linux-64