Required:
  receptor: protein.pdb
  ligand: ligand.sdf
  ligand_batch: null
  center: [9.028, 0.804, 21.789]
Advanced:
  exhaustiveness: 512
  randomize: true
  mc_steps: 20
  opt_steps: -1
  refine_steps: 5
  num_pose: 10
  rmsd_limit: 1.0
  energy_range: 3.0
  seed: 12345
  use_tor_lib: false
Hardware:
  gpu_device_id: 0
Settings:
  box_size: [30.0, 30.0, 30.0]
  task: screen
  search_mode: balance
Preprocessing:
  template_docking: true
  reference_sdf_file_name: reference.sdf
  compute_center: true
  core_atom_mapping_dict_list: [{'0': 14,
    '1': 15,
    '10': 11,
    '11': 12,
    '12': 13,
    '16': 1,
    '17': 2,
    '18': 3,
    '19': 4,
    '20': 6,
    '21': 7,
    '22': 8,
    '23': 9,
    '24': 20,
    '25': 21,
    '27': 27,
    '6': 24,
    '7': 0,
    '8': 5,
    '9': 10}]
  covalent_ligand: false
  covalent_residue_atom_info_list: null
  preserve_receptor_hydrogen: true
  temp_dir_name: /tmp
  output_docking_pose_sdf_file_name: unidock2_pose.sdf
