Required:
  receptor: 5WIU_protein_water_cleaned.pdb
  ligand: actives_cleaned.sdf
  ligand_batch: null
  center: [-18.0, 15.2, -17.0]
Advanced:
  exhaustiveness: 512
  randomize: true
  mc_steps: 20
  opt_steps: -1
  refine_steps: 5
  num_pose: 10
  rmsd_limit: 1.0
  energy_range: 3.0
  seed: 12345
  use_tor_lib: false
Hardware:
  gpu_device_id: 0
Settings:
  box_size: [30.0, 30.0, 30.0]
  task: screen
  search_mode: balance
Preprocessing:
  template_docking: false
  reference_sdf_file_name: null
  compute_center: true
  core_atom_mapping_dict_list: null
  covalent_ligand: false
  covalent_residue_atom_info_list: null
  preserve_receptor_hydrogen: false
  remove_temp_files: true
  temp_dir_name: /tmp
  output_docking_pose_sdf_file_name: unidock2_pose.sdf
